categories:
- Transcriptomics
description: Wrapper for the R package tximport
homepage_url: https://github.com/mikelove/tximport
remote_repository_url: https://github.com/ieguinoa/tximport-galaxy-wrapper
name: tximport
owner: ieguinoa
type: unrestricted
long_description: |
    Imports transcript-level abundance, estimated counts and transcript lengths, and summarizes into matrices for use with downstream statistical analysis packages such as edgeR, DESeq2, limma-voom. Average transcript length, weighted by sample-specific transcript abundance estimates, is provided as a matrix which can be used as an offset for different expression of gene-level counts.
